package com.otherhy.bos.domain.user;
// Generated 2017-8-6 14:40:39 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name="T_USER"
    ,schema="SCOTT"
    , uniqueConstraints = {@UniqueConstraint(columnNames="EMAIL"), @UniqueConstraint(columnNames="TELEPHONE")} 
)
public class User implements java.io.Serializable {


     private BigDecimal id;
     private String email;
     private String password;
     private BigDecimal salary;
     private Date birthday;
     private String sex;
     private String station;
     private String telephone;
     private String remark;

    public User() {
    }

	
    public User(BigDecimal id) {
        this.id = id;
    }
    public User(BigDecimal id, String email, String password, BigDecimal salary, Date birthday, String sex, String station, String telephone, String remark) {
       this.id = id;
       this.email = email;
       this.password = password;
       this.salary = salary;
       this.birthday = birthday;
       this.sex = sex;
       this.station = station;
       this.telephone = telephone;
       this.remark = remark;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    
    @Column(name="EMAIL", unique=true, length=30)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PASSWORD", length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="SALARY", precision=10)
    public BigDecimal getSalary() {
        return this.salary;
    }
    
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="BIRTHDAY", length=7)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    
    @Column(name="SEX", length=2)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="STATION", length=30)
    public String getStation() {
        return this.station;
    }
    
    public void setStation(String station) {
        this.station = station;
    }
    
    @Column(name="TELEPHONE", unique=true, length=11)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
    @Column(name="REMARK", length=50)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }




}


